INFO:     Will watch for changes in these directories: ['/home/deploy/bakery']
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [4012] using WatchFiles
/home/deploy/bakery/backend/venv/lib/python3.12/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:
* 'orm_mode' has been renamed to 'from_attributes'
  warnings.warn(message, UserWarning)
INFO:     Started server process [4014]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     127.0.0.1:46190 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:46190 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:41772 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:41798 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:52184 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:52206 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:57048 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:57072 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:45588 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:45612 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:50680 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:50690 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:35334 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:35370 - "GET / HTTP/1.1" 200 OK
WARNING:  WatchFiles detected changes in 'backend/seed.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [4014]
/home/deploy/bakery/backend/venv/lib/python3.12/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:
* 'orm_mode' has been renamed to 'from_attributes'
  warnings.warn(message, UserWarning)
INFO:     Started server process [6736]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     127.0.0.1:33862 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:33894 - "GET / HTTP/1.1" 200 OK
WARNING:  WatchFiles detected changes in 'backend/seed.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [6736]
/home/deploy/bakery/backend/venv/lib/python3.12/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:
* 'orm_mode' has been renamed to 'from_attributes'
  warnings.warn(message, UserWarning)
INFO:     Started server process [6788]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  WatchFiles detected changes in 'backend/models.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [6788]
/home/deploy/bakery/backend/venv/lib/python3.12/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:
* 'orm_mode' has been renamed to 'from_attributes'
  warnings.warn(message, UserWarning)
INFO:     Started server process [6816]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     127.0.0.1:46436 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:46436 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:43628 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:46436 - "GET / HTTP/1.1" 200 OK
WARNING:  WatchFiles detected changes in 'backend/models.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [6816]
/home/deploy/bakery/backend/venv/lib/python3.12/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:
* 'orm_mode' has been renamed to 'from_attributes'
  warnings.warn(message, UserWarning)
INFO:     Started server process [6894]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     127.0.0.1:38986 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:50012 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:50032 - "GET /products HTTP/1.1" 200 OK
INFO:     127.0.0.1:52976 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:52998 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:44578 - "POST /orders HTTP/1.1" 422 Unprocessable Entity
INFO:     127.0.0.1:40800 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:40832 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:60758 - "GET / HTTP/1.1" 200 OK
WARNING:  WatchFiles detected changes in 'backend/app.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [6894]
/home/deploy/bakery/backend/venv/lib/python3.12/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:
* 'orm_mode' has been renamed to 'from_attributes'
  warnings.warn(message, UserWarning)
INFO:     Started server process [7101]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     127.0.0.1:42334 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:42374 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:45978 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:46010 - "GET / HTTP/1.1" 200 OK
WARNING:  WatchFiles detected changes in 'backend/app.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [7101]
/home/deploy/bakery/backend/venv/lib/python3.12/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:
* 'orm_mode' has been renamed to 'from_attributes'
  warnings.warn(message, UserWarning)
INFO:     Started server process [7325]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     127.0.0.1:44820 - "GET /products HTTP/1.1" 200 OK
INFO:     127.0.0.1:44832 - "POST /orders HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/deploy/bakery/backend/venv/lib/python3.12/site-packages/uvicorn/protocols/http/httptools_impl.py", line 409, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/deploy/bakery/backend/venv/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/deploy/bakery/backend/venv/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/deploy/bakery/backend/venv/lib/python3.12/site-packages/starlette/applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/deploy/bakery/backend/venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/home/deploy/bakery/backend/venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/home/deploy/bakery/backend/venv/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 63, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/deploy/bakery/backend/venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/home/deploy/bakery/backend/venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/home/deploy/bakery/backend/venv/lib/python3.12/site-packages/starlette/routing.py", line 716, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/deploy/bakery/backend/venv/lib/python3.12/site-packages/starlette/routing.py", line 736, in app
    await route.handle(scope, receive, send)
  File "/home/deploy/bakery/backend/venv/lib/python3.12/site-packages/starlette/routing.py", line 290, in handle
    await self.app(scope, receive, send)
  File "/home/deploy/bakery/backend/venv/lib/python3.12/site-packages/starlette/routing.py", line 78, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/deploy/bakery/backend/venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/home/deploy/bakery/backend/venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/home/deploy/bakery/backend/venv/lib/python3.12/site-packages/starlette/routing.py", line 75, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "/home/deploy/bakery/backend/venv/lib/python3.12/site-packages/fastapi/routing.py", line 302, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/deploy/bakery/backend/venv/lib/python3.12/site-packages/fastapi/routing.py", line 215, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/deploy/bakery/backend/venv/lib/python3.12/site-packages/starlette/concurrency.py", line 38, in run_in_threadpool
    return await anyio.to_thread.run_sync(func)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/deploy/bakery/backend/venv/lib/python3.12/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/deploy/bakery/backend/venv/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 2476, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/home/deploy/bakery/backend/venv/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 967, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/deploy/bakery/backend/app.py", line 115, in create_order
    db.add(OrderItem(
           ^^^^^^^^^^
  File "<string>", line 4, in __init__
  File "/home/deploy/bakery/backend/venv/lib/python3.12/site-packages/sqlalchemy/orm/state.py", line 571, in _initialize_instance
    with util.safe_reraise():
  File "/home/deploy/bakery/backend/venv/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 224, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/deploy/bakery/backend/venv/lib/python3.12/site-packages/sqlalchemy/orm/state.py", line 569, in _initialize_instance
    manager.original_init(*mixed[1:], **kwargs)
  File "/home/deploy/bakery/backend/venv/lib/python3.12/site-packages/sqlalchemy/orm/decl_base.py", line 2179, in _declarative_constructor
    raise TypeError(
TypeError: 'price' is an invalid keyword argument for OrderItem
INFO:     127.0.0.1:44844 - "POST /orders//confirm HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:50642 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:33594 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:47596 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:47622 - "GET / HTTP/1.1" 200 OK
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [7325]
INFO:     Stopping reloader process [4012]
